[package]
name = "nightcycle/timesync"
description = "a really basic way to ensure clients and servers get the same tick"
version = "0.1.2"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Signal = "nightcycle/signal@1.0.2"
Maid = "nightcycle/maid@1.0.4"
NetworkUtil = "nightcycle/network-util@1.3.3"